### ISSUE TITLE
Meva datasets 

### ISSUE THREAD

**Issue by Lvqin001** [amazon-research/tracking-dataset#2]
Excuse me, I don't have an aws iam account. Can you provide some original video data of Meva? Google Cloud or Baidu Cloud can be used.

**Comment by Lvqin001** [comment]
run download.py download meva success.

**Comment by bingshuai2019** [comment]
Yes, the downloading script should be able to handle downloading all sources of data.

Let me know if you came across issues downloading the data. 

Now, I'm closing this thread as the issue has been resolved.
